version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fraud-dashboard"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iampa5gtp9q0"
s3_prefix = "fraud-dashboard"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["WhoisFunction=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/whoisfunctionc5253cb1repo", "AddDomain=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/adddomain87acfd1brepo", "GetTldPrice=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/gettldprice1926c114repo", "GetDomains=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/getdomainsbf3ce1e0repo", "GetDomain=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/getdomaindea0676brepo", "GetCategoryCost=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/getcategorycost9909736drepo", "GetDomainData=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/getdomaindata8933e958repo", "GetAllCategoryData=954605324087.dkr.ecr.eu-west-1.amazonaws.com/frauddashboardb7deefac/getallcategorydata40a27ad6repo"]
