version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fraud-dashboard"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5wj302kjkviw"
s3_prefix = "fraud-dashboard"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
