AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fraud_investments

  Sample SAM Template for fraud_investments

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WhoisFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        WhoIs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /whois
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./whois
      DockerTag: python3.9-v1

  AddDomain:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonRoute53DomainsReadOnlyAccess
      Events:
        AddDomainAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /add-domain
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./add_domain
      DockerTag: python3.9-v1

  GetTldPrice:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 10
      Policies:
      - AmazonRoute53DomainsReadOnlyAccess
      Events:
        TLDPriceAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get-tld-price
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./get_tld_price
      DockerTag: python3.9-v1

Outputs:
  WhoIsApi:
    Description: "API Gateway endpoint URL for Prod stage for WhoIs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/whois/"
  WhoisFunction:
    Description: "Whois Lambda Function ARN"
    Value: !GetAtt WhoisFunction.Arn
  WhoisFunctionIamRole:
    Description: "Implicit IAM Role created for Multiply function"
    Value: !GetAtt WhoisFunctionRole.Arn
  AddDomainAPI:
    Description: "API Gateway endpoint URL for Prod stage for addDomain function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add-domain/"
  AddDomain:
    Description: "addDomain Lambda Function ARN"
    Value: !GetAtt AddDomain.Arn
  AddDomainIamRole:
    Description: "Implicit IAM Role created for Multiply function"
    Value: !GetAtt AddDomainRole.Arn
  GetTLDPriceAPI:
    Description: "API Gateway endpoint URL for Prod stage for getTLDPrice function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-tld-price/"
  GetTldPrice:
    Description: "getTldPrice Lambda Function ARN"
    Value: !GetAtt GetTldPriceRole.Arn
  GetTldPriceIamRole:
    Description: "Implicit IAM Role created for Multiply function"
    Value: !GetAtt GetTldPriceRole.Arn
